VSCODIUM_VER="1.109.41146"
HOST_WORKSPACE="${HOME}/github"
CLIENT_USERNAME="codium"
HOST_VSCODIUM_CONFIG_DIR="${HOME}/.config/VSCodium2"
HOST_VSCODIUM_VSCODE_OSS_DIR="${HOME}/.vscode-oss.VSCodium2"
REMOSS_REMOTE_NAME="reh-server"
REMOSS_REMOTE_PORT="11111"
REMOSS_REMOTE_HOST="127.0.0.1"
VSCODIUM_REH_SERVER_HOST="127.0.0.1"
VSCODIUM_REH_SERVER_PORT="11111"


