ARG VSCODIUM_VER=${VSCODIUM_VER}
FROM vscodium-dockerfied-base-${VSCODIUM_VER}.img:latest

USER root
RUN apt-get update && apt-get install -y jq

USER ${CLIENT_USERNAME}

ARG CACHE_BUST=9

# Create directory and set it as working directory
RUN mkdir -p /home/${CLIENT_USERNAME}/.vsix-tmp
WORKDIR /home/${CLIENT_USERNAME}/.vsix-tmp

# Download and verify extension - all these commands run in /home/${CLIENT_USERNAME}/.vsix-tmp

RUN curl -L --fail --show-error --retry 5 -o xaberus.remote-oss-0.0.5.vsix \
    https://open-vsx.org/api/xaberus/remote-oss/0.0.5/file/xaberus.remote-oss-0.0.5.vsix || exit 1

# COPY will put files in /home/${CLIENT_USERNAME}/.vsix-tmp because thats our working directory

COPY --chown=${CLIENT_USERNAME}:${CLIENT_USERNAME} xaberus.remote-oss-0.0.5.vsix.sha256 ./xaberus.remote-oss-0.0.5.vsix.256
RUN [ -f xaberus.remote-oss-0.0.5.vsix ] && sha256sum -c xaberus.remote-oss-0.0.5.vsix.256 || exit 1

ARG CACHE_BUST=7
# Install extension and clean up - still in /home/${CLIENT_USERNAME}/.vsix-tmp
RUN codium --install-extension xaberus.remote-oss-0.0.5.vsix && \
    rm -rf ./*        # ./* refers to all files in /home/${CLIENT_USERNAME}/.vsix-tmp

ARG CACHE_BUST=5
RUN test ${CACHE_BUST} -ne 0 || echo never

# Change working directory for copying files
WORKDIR /home/${CLIENT_USERNAME}

# Problem: ~/.vscode-oss/argv.json gets overwritten by vscodium on startup.
# Solution: config-vscode-oss-argv-json.sh amd merge-xaberus-remote-oss.sh
#    enables ~/.vscode-oss/argv.json to be modifed with the necessary settings for extension
#    xaberus.vscode-oss to be inserted into ~/.vscode-oss/argv.json, avoid by hand addition on every startup.

COPY --chown=${CLIENT_USERNAME}:${CLIENT_USERNAME} start-vscodium-remoss-client.sh config-vscode-oss-argv-json.sh merge-xaberus-remote-oss.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/start-vscodium-remoss-client.sh /usr/local/bin/config-vscode-oss-argv-json.sh /usr/local/bin/merge-xaberus-remote-oss.sh

ENTRYPOINT ["/usr/local/bin/start-vscodium-remoss-client.sh"]