ARG VSCODIUM_VER=1.109.41146
FROM vscodium-dockerfied-base-${VSCODIUM_VER}.img:latest

USER ${CLIENT_USERNAME}

COPY --chown=${CLIENT_USERNAME}:${CLIENT_USERNAME} vscodium-standalone-start.sh /usr/local/bin/vscodium-standalone-start.sh
RUN chmod +x /usr/local/bin/vscodium-standalone-start.sh

ENTRYPOINT ["/usr/local/bin/vscodium-standalone-start.sh"]
